channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - setuptools>=65.5.0
  - mlflow==2.16.0
  - azureml-mlflow
  - azureml-core
  - azureml-dataset-runtime[fuse]
  - azure-ai-ml
  - azure-identity
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.1.4
  - scipy==1.11.4
  - scikit-learn==1.4.2
  - pyarrow==14.0.2
  - psutil==5.9.8
name: mlflow-env
