name: Monitor Drift
on:
  schedule: 
    - cron: '0 0 * * 1' # mỗi thứ 2 
jobs:
  run-monitor-drift:
    runs-on: ubuntu-latest 
    environment: Production 
    env:
      AZURE_STORAGE_ACCOUNT: ${{secrets.AZURE_STORAGE_ACCOUNT}}
      AZURE_STORAGE_SAS_TOKEN_LOGS: ${{secrets.AZURE_STORAGE_SAS_TOKEN_LOGS}}
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - run: pip install -r monitoring/requirements.txt 
      - run: python monitoring/drift_monitor.py
